# Generated by Django 4.0.5 on 2022-06-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.state', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=200, unique=True, verbose_name='Область'),
        ),
    ]
