# Generated by Django 4.0.5 on 2022-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_city_osm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
