# Generated by Django 4.0.5 on 2022-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_city_lat_city_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес'),
        ),
    ]
