# Generated by Django 4.0.5 on 2022-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_id',
            field=models.CharField(default=1, max_length=30, verbose_name='Id Адреса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='profile',
            name='boundingbox',
            field=models.CharField(default=1, max_length=500, verbose_name='Координаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
