# Generated by Django 4.0.5 on 2022-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_address_id_profile_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Id Адреса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='boundingbox',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lon',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
